INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Accounting and Finance');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Allied Health and Human Performance');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Anthropology, Economics and Political Science');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Arts and Cultural Management');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Biological Sciences');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Child and Youth Care');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Communication');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Computer Science');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Decision Sciences');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Design');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of English');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Health Systems and Sustainability');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Human Health and Science');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Human Services and Early Learning');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Humanities');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of International Business, Marketing, Strategy and Law');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Management and Organizations');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Mathematics and Statistics');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Music');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Nursing Foundations');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Nursing Practice');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Physical Sciences');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Professional Nursing and Allied Health');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Psychology');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Public Safety and Justice Studies');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Sociology');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Studio Arts');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('Department of Theatre');
INSERT INTO [dbo].[department] ([deptName]) VALUES ('School of Social Work');